---
title: ""
format:
  html:
    theme: flatly
    toc: false
    page-layout: full
    number-sections: false
    css: /CSS/my-fonts.css
    header-includes: |
      <!-- Bootstrap Icons -->
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css">



fontsize: 12pt
geometry: margin=1in


---
#### <i class="bi bi-file-text"></i> Publications

<div id="publications-container">

<div class="article-card">
  <h4>Using Machine Learning Methods to Model and Interpret Problems in Determining the Parameters of the Medium Near the Well Using Signals from a High-Frequency Induction Logging While Drilling Device</h4>
  <p>Author(s): Alexander Vlasov, Rofikul Masud, Galina Bykova<br>
  <em>2025 IEEE XVII International Scientific and Technical Conference on Actual Problems of Electronic Instrument Engineering (APEIE)</em></p>
  
  <a href="mailto:r.ben.masud@gmail.com?subject=Request%20for%20Paper%20-%20Vlasov%20et%20al%202025&body=Hello,%0D%0A%0D%0AI%20would%20like%20to%20request%20a%20copy%20of%20the%20paper%20titled%20'Using%20Machine%20Learning%20Methods%20to%20Model%20and%20Interpret%20Problems...'." target="_blank" class="article-card-link">
    <i class="bi bi-envelope"></i> Request the Paper
  </a>
  <a href="#" target="_blank" class="article-card-link">
    <i class="bi bi-quote"></i> Cite This
  </a>
</div>

<br>

</div>

#### <i class="bi bi-pc-display"></i> Software Patent

<div id="software-patents-container">

<div class="article-card">
  <h4>BIS – Fast Interpretation of High-Frequency Electromagnetic Sounding Data</h4>
  <p>Author(s): Galina Bykova (RU), Alexander Vlasov (RU), Rofikul Masud (BD)<br>
  <em>Registered Computer Program, Russian Federation, Certificate No. 2024687640, 11/20/2024</em></p>
  
  <p>Software for digital processing of high-frequency electromagnetic sounding signals during horizontal wellbore drilling. Functionalities include searching for model parameters matching experimental signals, calculating signals for individual models, and evaluating target functions. Operates with interval two-layer models considering layer resistance, anisotropy, dip angle, and depth. Compatible with Windows 10+, written in C++.</p>
  
  <a href="mailto:r.ben.masud@gmail.com?subject=Request%20for%20Software%20-%20BIS&body=Hello,%0D%0A%0D%0AI%20would%20like%20to%20request%20a%20copy%20of%20the%20software%20'BIS'." target="_blank" class="article-card-link">
    <i class="bi bi-envelope"></i> Request the File
  </a>

</div>

</div>